import React, { useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { getIncidentReport } from '../api/incidents';
import { LoadingSpinner } from '../components/common/LoadingSpinner';
import { ErrorBanner } from '../components/common/ErrorBanner';
import { FileText, Copy, ArrowLeft, Download } from 'lucide-react';
import { generateAlertReport } from '../utils/exporters'; // We'll adapt this for the report or just use native window.print()

const IncidentReport = () => {
    const { id } = useParams();
    const { data: reportData, isLoading, isError } = useQuery({
        queryKey: ['incidentReport', id],
        queryFn: () => getIncidentReport(id),
        retry: false
    });

    const [activeTab, setActiveTab] = useState('ips');

    if (isLoading) return <LoadingSpinner />;
    if (isError || !reportData?.data) return <ErrorBanner message="Report not found or is still generating. Please try again later." />;

    const report = reportData.data;

    const copyMarkdown = () => {
        const md = `# Incident Report: ${report.incident_id}\\n\\n` +
                   `**Generated At:** ${new Date(report.generated_at).toLocaleString()}\\n` +
                   `**Generated By:** ${report.generated_by}\\n\\n` +
                   `## Executive Summary\\n${report.executive_summary}\\n\\n` +
                   `## Technical Analysis\\n${report.technical_analysis}\\n\\n` +
                   `## Recommended Actions\\n` + report.recommended_actions.map((r, i) => `${i+1}. ${r}`).join("\\n") + `\\n\\n` +
                   `## Severity Justification\\n${report.severity_justification}\\n\\n` +
                   `## Indicators of Compromise\\n` +
                   `- **IPs**: ${report.indicators_of_compromise.ips.join(", ") || "None"}\\n` +
                   `- **Processes**: ${report.indicators_of_compromise.processes.join(", ") || "None"}\\n` +
                   `- **Techniques**: ${report.indicators_of_compromise.techniques.join(", ") || "None"}\\n`;
        
        navigator.clipboard.writeText(md);
        alert("Markdown copied to clipboard!");
    };

    const handlePrint = () => {
        window.print();
    };

    return (
        <div className="bg-gray-100 min-h-screen py-8 -m-8 text-black font-serif print:bg-white print:m-0 print:py-0">
            <div className="max-w-4xl mx-auto bg-white p-12 shadow-xl print:shadow-none print:p-0">
                {/* Print hidden controls */}
                <div className="flex justify-between items-center mb-12 print:hidden border-b pb-4">
                    <Link to="/incidents" className="flex items-center text-blue-600 hover:text-blue-800 text-sm font-sans font-medium">
                        <ArrowLeft className="h-4 w-4 mr-1" /> Back to Incidents
                    </Link>
                    <div className="flex gap-4">
                        <button onClick={copyMarkdown} className="flex items-center gap-2 text-sm bg-gray-100 hover:bg-gray-200 text-gray-800 px-4 py-2 rounded-lg font-sans transition-colors">
                            <Copy className="h-4 w-4" /> Copy Markdown
                        </button>
                        <button onClick={handlePrint} className="flex items-center gap-2 text-sm bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg font-sans transition-colors">
                            <Download className="h-4 w-4" /> Export PDF
                        </button>
                    </div>
                </div>

                {/* Report Header */}
                <div className="border-b-2 border-black pb-6 mb-8 flex justify-between items-end">
                    <div>
                        <h1 className="text-4xl font-bold text-gray-900 mb-2">Automated Incident Report</h1>
                        <p className="text-xl text-gray-600 font-medium">Incident: <span className="font-mono bg-gray-100 px-2">{report.incident_id}</span></p>
                    </div>
                    <div className="text-right text-sm text-gray-500">
                        <p><strong>Generated:</strong> {new Date(report.generated_at).toLocaleString()}</p>
                        <p><strong>Engine:</strong> {report.generated_by}</p>
                    </div>
                </div>

                {/* Section: Executive Summary */}
                <div className="mb-8">
                    <h2 className="text-2xl font-bold text-gray-900 border-b border-gray-300 pb-2 mb-4 uppercase tracking-wider text-sm">1. Executive Summary</h2>
                    <p className="text-gray-800 leading-relaxed text-lg">{report.executive_summary}</p>
                </div>

                {/* Section: Severity Justification */}
                <div className="mb-8 bg-gray-50 p-4 border-l-4 border-gray-800">
                    <h3 className="text-sm font-bold text-gray-900 uppercase mb-2">Severity Justification</h3>
                    <p className="text-gray-800 italic">{report.severity_justification}</p>
                </div>

                {/* Section: Technical Analysis */}
                <div className="mb-10">
                    <h2 className="text-2xl font-bold text-gray-900 border-b border-gray-300 pb-2 mb-4 uppercase tracking-wider text-sm">2. Technical Analysis</h2>
                    <p className="text-gray-800 leading-relaxed whitespace-pre-wrap">{report.technical_analysis}</p>
                </div>

                {/* Section: Timeline */}
                <div className="mb-10">
                    <h2 className="text-2xl font-bold text-gray-900 border-b border-gray-300 pb-2 mb-4 uppercase tracking-wider text-sm">3. Attack Timeline</h2>
                    <ul className="space-y-4">
                        {report.attack_timeline.map((event, idx) => (
                            <li key={idx} className="flex gap-4">
                                <span className="font-mono text-gray-500 whitespace-nowrap">{new Date(event.timestamp).toLocaleString()}</span>
                                <span className="text-gray-900">
                                    <span className="font-bold mr-2">[{event.threat_level.toUpperCase()}]</span>
                                    {event.event}
                                </span>
                            </li>
                        ))}
                    </ul>
                </div>

                {/* Section: IOCs */}
                <div className="mb-10">
                    <h2 className="text-2xl font-bold text-gray-900 border-b border-gray-300 pb-2 mb-4 uppercase tracking-wider text-sm">4. Indicators of Compromise</h2>
                    
                    <div className="border border-gray-300 rounded font-sans">
                        <div className="flex border-b border-gray-300 bg-gray-50">
                            <button onClick={() => setActiveTab('ips')} className={`flex-1 py-2 text-sm font-bold ${activeTab === 'ips' ? 'text-blue-700 border-b-2 border-blue-700 bg-white' : 'text-gray-500'}`}>IP Addresses ({report.indicators_of_compromise.ips.length})</button>
                            <button onClick={() => setActiveTab('processes')} className={`flex-1 py-2 text-sm font-bold ${activeTab === 'processes' ? 'text-blue-700 border-b-2 border-blue-700 bg-white' : 'text-gray-500'}`}>Processes ({report.indicators_of_compromise.processes.length})</button>
                            <button onClick={() => setActiveTab('techniques')} className={`flex-1 py-2 text-sm font-bold ${activeTab === 'techniques' ? 'text-blue-700 border-b-2 border-blue-700 bg-white' : 'text-gray-500'}`}>MITRE ATT&CK ({report.indicators_of_compromise.techniques.length})</button>
                        </div>
                        <div className="p-4 bg-white min-h-[150px]">
                            {activeTab === 'ips' && (
                                <ul className="list-disc pl-5 font-mono text-sm space-y-1">
                                    {report.indicators_of_compromise.ips.map((ip, i) => <li key={i}>{ip}</li>)}
                                    {report.indicators_of_compromise.ips.length === 0 && <span className="text-gray-400 italic">No IPs logged.</span>}
                                </ul>
                            )}
                            {activeTab === 'processes' && (
                                <ul className="list-disc pl-5 font-mono text-sm space-y-1">
                                    {report.indicators_of_compromise.processes.map((proc, i) => <li key={i}>{proc}</li>)}
                                    {report.indicators_of_compromise.processes.length === 0 && <span className="text-gray-400 italic">No processes logged.</span>}
                                </ul>
                            )}
                            {activeTab === 'techniques' && (
                                <ul className="list-disc pl-5 font-mono text-sm space-y-1">
                                    {report.indicators_of_compromise.techniques.map((tech, i) => <li key={i}>{tech}</li>)}
                                    {report.indicators_of_compromise.techniques.length === 0 && <span className="text-gray-400 italic">No techniques logged.</span>}
                                </ul>
                            )}
                        </div>
                    </div>
                </div>

                {/* Section: Recommendations */}
                <div className="mb-10">
                    <h2 className="text-2xl font-bold text-gray-900 border-b border-gray-300 pb-2 mb-4 uppercase tracking-wider text-sm">5. Recommended Actions</h2>
                    <ul className="list-decimal pl-6 space-y-3 text-gray-800">
                        {report.recommended_actions.map((rec, idx) => (
                            <li key={idx} className="pl-2">{rec}</li>
                        ))}
                    </ul>
                </div>
            </div>
        </div>
    );
};

export default IncidentReport;
